<table class="table table-striped small">
    <thead>
    <tr>
        <th><?=$this->moduleLanguage['clients_form_soc_acc']?></th>
        <th style="text-align:right;"><?=$this->moduleLanguage['clients_form_contacts_action']?></th>
    </tr>
    </thead>
    <tbody>
    <?if($this->social):?>
        <?foreach($this->social as $val):?>
            <tr>
                <td><?=$val['soc_acc']?></td>
                <td><a style="cursor: pointer;" data-pk="<?=$val['id']?>" class="socdel"><?=$this->moduleLanguage['clients_form_contacts_delete']?></a></td>
            </tr>
        <?endforeach;?>
    <?endif;?>
    </tbody>
</table>
<div class="loading social"></div>
<script type="text/javascript">
    $(document).ready(function()
    {
        $('a.socdel').click(function()
        {
            del_id = $(this).data('pk');
            $('div.loading.social').css('display', 'block');
            $.ajax({
                url: BASE_URL + '/clients/deleteSocial/' + del_id,
                success: function(jsonData)
                {
                    if(jsonData)
                        alert(jsonData);
                    getSocials();
                },
                dataType: 'html'
            });
        });
    });
</script>