<div class="col-md-12 buttons">
    <a class="btn btn-primary save" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['templates_save']?></a>
    <a class="btn btn-success save-exit" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['templates_save_and_exit']?></a>
    <a class="btn btn-success save-add" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['templates_save_and_create']?></a>
    <a class="btn btn-danger  exit" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'templates/';?>"><?=$this->moduleLanguage['templates_exit']?></a>
</div>
<form name="editForm" method="POST">
    <input type="hidden" name="author" value="<?=$this->data->_author ? $this->data->_author : $this->userInfo['id'];?>">
    <input type="hidden" name="action" value="<?=Request::instance()->getAction();?>">
    <div class="content-block col-md-12">
        <div class="form-group col-md-4">
            <label><?=$this->moduleLanguage['templates_form_name']?></label>
            <input type="text" name="name" class="form-control" value="<?=$this->data->_name?>" placeholder="<?=$this->moduleLanguage['templates_form_name_placeholder']?>">
        </div> 
        <?if(Request::instance()->getAction() == 'add'):?>
        <div class="form-group col-md-12">
            <label><?=$this->moduleLanguage['templates_form_warning']?></label>
        </div>
        <?else:?>
        <div class="form-group col-md-2">
            <label><?=$this->moduleLanguage['templates_form_module']?></label>
            <select class="form-control" name="mod_name">
                <?=models_helpers_Options::basicOptions(models_helpers_Options::getModulesNames(),'','',$this->moduleLanguage['templates_form_module_placeholder'])?>
            </select>
        </div>
        <div class="form-group col-md-2">
            <label><?=$this->moduleLanguage['templates_form_position']?></label>
            <select class="form-control" name="position">
                <?=models_helpers_Options::basicOptions(models_helpers_Options::getPositions(),'','',$this->moduleLanguage['templates_form_position_placeholder'])?>
            </select>
        </div>
        <div class="form-group col-md-2">
            <label><?=$this->moduleLanguage['templates_form_order']?></label>
            <input type="text" name="pos_order" class="form-control">
        </div>
        <a type="submit" class="btn btn-primary upload-tpl col-md-1"><?=$this->moduleLanguage['templates_form_add']?></a>
        <?endif;?>
        <div id="modules" class="ajax-bottom"></div>
    </div>
</form>
<script type="text/javascript">
var id = <?=$this->data->_id?>;

$(document).ready(function()
{
    $('a.upload-tpl').on('click', function(e)
    {
        e.preventDefault();   
        $('div.loading').css('display', 'block');
        var data = new FormData();
        // присвоение данных таблицы для отправки постом
        data.append('mod_name', $('select[name="mod_name"]').val());
        data.append('position', $('select[name="position"]').val());
        data.append('pos_order', $('input[name="pos_order"]').val());

        $.ajax({
            type: 'POST',               
            processData: false,
            contentType: false,
            data: data,
            url: BASE_URL + '/templates/templateModule/' + id,
            success: function(jsonData)
            {
                if(jsonData)
                    alert(jsonData);
                getModules();
            }
        }); 
    });  
});

getModules();
// вызов картинок материала
function getModules()
{
    $.get(BASE_URL + '/templates/getlist/' + id, null, function(data)
    {
        $('.col-md-12 #modules').html(data);
    });
}
</script>