<?if(@$this->Msg):?>
    <div class="login-form-header"><?=$this->Msg?></div>
<?endif;?>
<div class="step-heading"><?=$this->moduleLanguage['change_pass']?></div>
<div class="row">
    <div class="col-sm-5">
        <form class="login-form" method="POST" action="/account/passwordChange">
            <?if (!empty ($this->pass)):?>
                <input type="password" name="existing_password" class="login-form-input" placeholder="<?=$this->moduleLanguage['existing_password']?>"required>
            <?endif;?>
            <input type="password" name="new_password" class="login-form-input" placeholder="<?=$this->moduleLanguage['new_pass_line']?>" required>
            <input type="password" name="password_check" class="login-form-input" placeholder="<?=$this->moduleLanguage['new_pass_repeat']?>" required>
            <button type="submit" name="savep" class="btn btn-custom-xs"><?=$this->moduleLanguage['save']?></button>
            <a href="/account/account" class="btn btn-custom-xs link"><?=$this->moduleLanguage['exit']?></a>
        </form>
    </div>
</div>

