<?if(@$this->content['msg']):?>
    <div class="message text-center"><?=$this->content['msg']?></div>
<?endif;?>
    <div class="row">
        <div class="col-sm-6">
            <form class="login-form" method="POST" action="/account/pass_reset">
                <input type="password" name="new_password" class="login-form-input" placeholder="<?=$this->moduleLanguage['new_pass_line']?>" required>
                <button type="submit" name="savep" class="btn btn-custom-xs"><?=$this->moduleLanguage['save']?></button>
            </form>
        </div>
    </div>
