<?$css = strpos($this->options['options_array'], 'css') ? true : false;?>
<?$this->options = unserialize($this->options['options_array']);?>
<table class="table table-striped small">
  <thead>
    <tr>
        <th style="text-align:center;">#</th>
        <th style="text-align:center;"><?=$this->moduleLanguage['parameters_form_option_val']?></th>
        <?if($css):?>
        <th style="text-align:center;"><?=$this->moduleLanguage['parameters_form_option_css']?></th>
        <?endif;?>
        <th style="text-align:center;"><?=$this->moduleLanguage['parameters_form_option_multiply']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['parameters_form_option_order']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['parameters_form_option_action']?></th>
    </tr>
  </thead>
  <tbody>
  <?if(!empty($this->options)):?>
  <?foreach($this->options as $key=>$val):?>
    <tr>
        <td align="center"><b><?=$key?></b></td>
        <td align="center"><?=$val['val']?></td>
        <td align="center"><?=$val['css']?></td>
        <?if($css):?>
        <td align="center"><?=$val['multiply']?></td>
        <?endif;?>
        <td align="center" style="vertical-align: middle;"><?=$val['order']?></td>
        <td align="center" style="vertical-align: middle;"><a style="cursor: pointer;" data-pk="<?=$key?>" class="moddel"><?=$this->moduleLanguage['parameters_form_delete']?></a></td>
    </tr>
    <?endforeach;?>
    <?endif;?>
  </tbody>
</table>
<div class="loading"></div>
<script type="text/javascript">
$(document).ready(function()
{
    $('a.moddel').click(function()
    {
        var key = $(this).data('pk');

        $('div.loading').css('display', 'block');
        $.ajax({
            url: BASE_URL + '/parameters/deleteOption/' + id,
            type: "POST",
            data: {data:key},
            complete: function()
            {
                getOptions();
            },
            dataType: 'html'
        });
    });
});
</script>