<div class="container">
    <div class="row">
        <div class="auth_title">
            <a href="/account/account">
                <?=(isset($_SESSION['default']['name'])) ? $this->moduleLanguage['my_acc'] : $this->moduleLanguage['authorization'] ?></a>
            <a href="/account/logout">
                <?if (isset ($_SESSION['default']['name'])) echo $this->moduleLanguage['logout'];?></a>
        </div>
    </div> <!--row-->
    <h3><?=$this->moduleLanguage['details']?></h3>
    <?foreach ($this->productInfo as $product):?>
        <div class="row">
            <div class="col-md-2">
                <img src="<?=$product['product_image']?>" class="product" alt="N/A">
            </div>
            <div class="col-md-6">
                <p><?=$product['product_name']?></p>
                <p><?=$this->moduleLanguage['cart_product_new_price']?>: <?=$product['new_price']?>$</p>
                <p><?=$this->moduleLanguage['cart_product_size']?>: <?=Session::instance()->get('size');?></p>
                <a class="btn btn-custom-xs product">
                    <p data-toggle="modal" data-target="#checkout"><?=$this->moduleLanguage['buy']?></p>
                </a>
                <a class="btn btn-custom-xs product" href="/cart/cancel"><?=$this->moduleLanguage['cancel']?></a>
            </div>
        </div><!-- row -->
    <?endforeach;?>
    <div class="modal fade" id="checkout" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><span><?=$this->moduleLanguage['checkout']?></span></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <form id="checkoutForm" method="post" action="/cart/addOrder">
                    <div class="modal-body row row-cart">
                        <div class="col-md-6">
                            <div class="form-group col-md-12">
                                <label><?=$this->moduleLanguage['fname']?> *</label>
                                <input type="text" name="f_name" required class="form-control" value = "<?=$this->customerInfo[0]['first_name']?>">
                            </div>
                            <div class="form-group col-md-12">
                                <label><?=$this->moduleLanguage['email']?> *</label>
                                <input type="email" name="email" required class="form-control" <?if(!empty($this->customerInfo[0]['email'])):?> value="<?=$this->customerInfo[0]['email']?>"<?endif;?> >
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group col-md-12">
                                <label><?=$this->moduleLanguage['lname']?> *</label>
                                <input type="text" name="l_name" required class="form-control" value = "<?=$this->customerInfo[0]['last_name']?>">
                            </div>
                            <div class="form-group col-md-12">
                                <label><?=$this->moduleLanguage['phone']?> *</label>
                                <input type="text" name="phone" required class="form-control" <?if(!empty($this->customerInfo[0]['phone'])):?> value="<?=$this->customerInfo[0]['phone']?>"<?endif;?> >
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <div class="col-md-12">
                                <label><?=$this->moduleLanguage['address']?> *</label>
                                <input type="text" name="address"  required class="form-control" <?if(!empty($this->customerInfo[0]['address'])):?> value="<?=$this->customerInfo[0]['address']?>"<?endif;?> >
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <div class="col-md-12">
                                <textarea class="form-control" name="comment" rows="3" placeholder="<?=$this->moduleLanguage['comment']?>"></textarea>
                            </div>
                        </div>
                        <div class="cart-total checkout">
                            <div class="text"><?=$this->moduleLanguage['total']?></div>
                            <div class="value"><?=$this->productInfo[0]['new_price']?>$</div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-custom-xs product"><p><?=$this->moduleLanguage['add_order']?></p></button>
                    </div>
                </form>
            </div> <!-- Modal content-->
        </div>
    </div> <!-- Modal -->
</div>
