<nav class="pag-container">
    <ul class="pagination">
        <?php if( $this->list['first'] ){?>
          <li class="first"><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->link . $this->list['first'] ?>">Первая</a></li>
        <?php }?>
        
        <?php if( $this->list['prev'] ){?>
          <li class="prev"><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->link . $this->list['prev'] ?>">«</a></li>
        <?php }?>
        
        <?php foreach( $this->list['items'] as $key => $val ){?>
          <?php if( $val != $this->list['current']){?>
            <li><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->link . $val ?>"><?php echo $val ?></a></li>
          <?php }else{ ?>
            <li class="active"><a href="#"><?php echo $val ?></a></li>
          <?php }?>
          
          <?php if( @$this->list['separator'][$key] ){?>
            <li class="empty"><a>...</a></li> 
          <?php }?>
          
        <?php }?>
        
    
        <?php if( $this->list['next'] ){?>
          <li class="next"><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->link . $this->list['next'] ?>">»</a></li>
        <?php }?>
        
        <?php if( $this->list['last'] ){?>
          <li class="last"><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->link . $this->list['last'] ?>">Последняя</a></li>
        <?php }?>
    </ul>
</nav>
