<link href="<?=CSS?>/chosen.css" rel="stylesheet">
<link href="<?=CSS?>/bootstrap-switch.css" rel="stylesheet">

<script src="<?=JS?>/highlight.js"></script>
<script src="<?=JS?>/bootstrap-switch.js"></script>
<script src="<?=JS?>/main.js"></script>
<script src="<?=JS?>/chosen.jquery.js"></script>
<script>
    $(function(){
        $(".chosen-select").chosen();
    });
</script>
<div class="col-md-12 buttons">
    <a class="btn btn-primary save" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['product_save']?></a>
    <a class="btn btn-success save-exit" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['product_save_and_exit']?></a>
    <a class="btn btn-success save-add" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['product_save_and_create']?></a>
    <a class="btn btn-danger  exit" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'product/';?>"><?=$this->moduleLanguage['product_exit']?></a>
</div>
<form name="editForm" method="POST">
    <input type="hidden" name="author" value="<?=$this->data->_author ? $this->data->_author : $this->userInfo['id'];?>">
    <input type="hidden" name="action" value="<?=Request::instance()->getAction();?>">
    <div class="content-block col-md-12">
        <div class="col-md-3">
            <div class="form-group col-md-12">
                <label><?=$this->moduleLanguage['product_form_name']?></label>
                <input type="text" name="name" class="form-control" value="<?=$this->data->_name?>" placeholder="<?=$this->moduleLanguage['product_form_name_placeholder']?>">
            </div>
            <div class="form-group col-md-12">
                <label><?=$this->moduleLanguage['product_form_image']?></label>
                <input type="text" name="image" class="form-control" onclick="openKCFinder(this)" value="<?=$this->data->_image?>" placeholder="<?=$this->moduleLanguage['product_form_image_placeholder']?>">
            </div>
            <div class="form-group col-md-12">
                <label class="center-block" style="text-align: center;"><?=$this->moduleLanguage['product_form_image_preview']?></label>
                <img width="128" class="img-thumbnail center-block" src="<?=$this->data->_image?>" />
            </div>
        </div>
        <div class="col-md-9">
            <?if(Request::instance()->getAction() == 'add'):?>
                <div class="form-group col-md-12">
                    <label><?=$this->moduleLanguage['product_form_warning']?></label>
                </div>
            <?else:?>
                <div class="form-group col-md-4">
                    <label><?=$this->moduleLanguage['productform_radio_type']?></label>
                    <input type="text" name="type" class="form-control" placeholder="<?=$this->moduleLanguage['product_form_radio_type_placeholder']?>">
                </div>
                <div class="form-group col-md-4">
                    <label><?=$this->moduleLanguage['product_form_radio_cat']?></label>
                    <select class="form-control chosen-select" name="cat"><?=models_helpers_Options::basicOptions(models_helpers_Options::getCategories(), @$filters['category'], 0, $this->moduleLanguage['content_search_category'])?>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label><?=$this->moduleLanguage['product_form_radio_image']?></label>
                    <input type="text" name="img" class="form-control" onclick="openKCFinder(this)" placeholder="<?=$this->moduleLanguage['product_form_radio_image_placeholder']?>">
                </div>
              <div class="form-group col-md-4">
                    <label><?=$this->moduleLanguage['productl_form_radio_price']?></label>
                    <input type="number" name="price" class="form-control" placeholder="<?=$this->moduleLanguage['product_form_radio_price_placeholder']?>">
                </div>
                <div class="form-group col-md-4">
                    <label><?=$this->moduleLanguage['product_form_radio_disc']?></label>
                     <input type="number" name="discount" class="form-control" placeholder="<?=$this->moduleLanguage['product_form_radio_disc_placeholder']?>">
                </div>
                <div class="form-group col-md-1">
                    <label><?=$this->moduleLanguage['product_form_radio_order']?></label>
                    <input type="number" name="order" class="form-control" placeholder="<?=$this->moduleLanguage['product_form_radio_order_placeholder']?>">
                </div>
                <a type="submit" class="btn btn-primary upload-opt col-md-2"><?=$this->moduleLanguage['product_form_add']?></a>
                <div id="options" class="ajax-bottom"></div>
            <?endif;?>
        </div>
    </div>
</form>
<script type="text/javascript">
    function openKCFinder(field)
    {
        window.KCFinder = {
            callBack: function(url)
            {
                field.value = url;
                window.KCFinder = null;
            }
        };
        window.open('<?=JS?>/kcfinder/browse.php?type=images&language=<?=strtolower(models_helpers_Url::getConfigLanguage())?>',
            'kcfinder_image', 'status=0, toolbar=0, location=0, menubar=0, ' +
            'directories=0, resizable=1, scrollbars=0, width=800, height=600'
        );
    }
    <?if(Request::instance()->getAction() == 'edit'):?>
    var id = <?=$this->data->_id?>;

    $(document).ready(function()
    {
        $('a.upload-opt').on('click', function(e)
        {
            e.preventDefault();
            $('div.loading').css('display', 'block');
            var data = new FormData();
            // allow form data
            data.append('type', $('input[name="type"]').val());
            data.append('cat', $('select[name="cat"]').val());
            data.append('img', $('input[name="img"]').val());
            data.append('price', $('input[name="price"]').val());
            data.append('discount', $('input[name="discount"]').val());
            data.append('order', $('input[name="order"]').val());
            if($('input[name="css"]').val())
                data.append('css', $('input[name="css"]').val());


            $.ajax({
                type: 'POST',
                processData: false,
                contentType: false,
                data: data,
                url: BASE_URL + '/product/addOption/' + id,
                success: function(jsonData)
                {
                    if(jsonData)
                        alert(jsonData);
                    getOptions();
                }
            });
        });
    });

    getOptions();
    // getting images
    function getOptions()
    {
        $.get(BASE_URL + '/product/getlist/' + id, null, function(data)
        {
            $('.col-md-12 #options').html(data);
        });
    }
    <?endif;?>
</script>