<link href="<?=CSS?>/chosen.css" rel="stylesheet">
<link href="<?=CSS?>/bootstrap-switch.css" rel="stylesheet">

<script src="<?=JS?>/bootstrap-switch.js"></script>
<script src="<?=JS?>/chosen.jquery.js"></script>
<script> 
$(function(){   
    $(".chosen-select").chosen();
    $("input[type=\"checkbox\"], input[type=\"radio\"]").not("[data-switch-no-init], input[name=\"select_all\"],input[name=\"dellist[]\"]").bootstrapSwitch();
});
</script>

<?php $filters = $this->filter->getData(); ?>
<form class="col-md-7 search-block" id="filter" action="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkForm()?>" method="post" onsubmit="return PathGenerator(this);">
    <div class="col-md-2">
        <select class="form-control" name="status"><?=models_helpers_Options::basicOptions(models_helpers_Options::statuses(), @$filters['status'], 0, $this->moduleLanguage['product_search_status'])?></select>
    </div>
    <div class="col-md-3">
        <select class="form-control chosen-select" name="category"><?=models_helpers_Options::basicOptions(models_helpers_Options::getCategories(), @$filters['category'], 0, $this->moduleLanguage['product_search_category'])?></select>
    </div>
    <div class="col-md-2" title="<?=$this->moduleLanguage['product_search_size']?>">
        <input type="radio" name="size" <?=@$filters['size'] ? 'checked' : ''?> data-radio-all-off="true"  class="switch-radio margin-left-no">
    </div>
    <div class="col-md-4">
        <div class="input-group">
            <input type="text" name="fulltext" value="<?=@$filters['fulltext']?>" class="form-control" placeholder="<?=$this->moduleLanguage['product_search_text']?>"/>
            <span class="input-group-btn">
            <input type="submit" class="btn btn-default" value="<?=$this->moduleLanguage['product_search_button']?>"/>
            </span>
        </div>    
    </div>
    <div class="col-md-1">
        <a href="#" class="clearSrch"><img src="<?=IMG?>/form/reset.png" title="<?=$this->moduleLanguage['product_search_reset']?>"/></a>
    </div>
</form>
<div class="col-md-5 buttons">
    <?if(models_helpers_Access::checkAccess('add')):?>
    <a class="btn btn-primary add" href="<?php echo models_helpers_Url::getValidBaseUrl().'product/add';?>"><?=$this->moduleLanguage['product_create']?></a>
    <?endif;?>
    <?if(models_helpers_Access::checkAccess('change_status')):?>
    <a class="btn btn-success activate" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'product/';?>"><?=$this->moduleLanguage['product_activation']?></a>
    <a class="btn btn-warning deactivate" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'product/';?>"><?=$this->moduleLanguage['product_deactivation']?></a>
    <a class="btn btn-danger  delete" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'product/';?>"><?=$this->moduleLanguage['product_delete']?></a>
    <?endif;?>
</div>
<div class="maincontent center-block">
<form method="post" name="baseform">
    <table class="table table-striped table-hover small">
        <thead>
            <tr>
                <th><input type="checkbox" class="dl" name="select_all" title="<?=$this->moduleLanguage['product_check_all']?>"></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('id') ?>" class="<?php echo $this->filter->checkSortOrder('id') ?>"><?=$this->moduleLanguage['product_table_id']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('name') ?>" class="<?php echo $this->filter->checkSortOrder('name') ?>"><?=$this->moduleLanguage['product_table_name']?></a></th>
                <th><?=$this->moduleLanguage['product_search_status']?></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('price') ?>" class="<?php echo $this->filter->checkSortOrder('price') ?>"><?=$this->moduleLanguage['product_table_price']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('vendor') ?>" class="<?php echo $this->filter->checkSortOrder('vendor') ?>"><?=$this->moduleLanguage['product_table_vendor']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('t3.name') ?>" class="<?php echo $this->filter->checkSortOrder('t3.name') ?>"><?=$this->moduleLanguage['product_table_category']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('main_lang') ?>" class="<?php echo $this->filter->checkSortOrder('main_lang') ?>"><?=$this->moduleLanguage['product_table_language']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('author') ?>" class="<?php echo $this->filter->checkSortOrder('author') ?>"><?=$this->moduleLanguage['product_table_author']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('t1.date_add') ?>" class="<?php echo $this->filter->checkSortOrder('t1.date_add') ?>"><?=$this->moduleLanguage['product_table_date']?></a></th> 
            </tr>
        </thead>
        <tbody>
        <?if($this->datalist):?>
        <?foreach($this->datalist as $key => $val):?>
            <tr>
                <td><input class="il" type="checkbox" name="dellist[]" value="<?=$val['id']?>"/></td>
                <th><?=$val['id']?></th>
                <td>
                    <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
                    <a href="<?=models_helpers_Url::getValidBaseUrl().'product/edit/'.$val['id']?>">
                    <?endif;?>
                    <?=$val['name']?>
                     <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
                    </a>
                    <?endif;?>
                </td>
                <td>
                    <?if(models_helpers_Access::checkAccess('change_status')):?>
                    <a href="<?=models_helpers_Url::getValidBaseUrl().'product/changeStatus/'.$val['id']?>">
                    <?endif;?>
                    <img src="<?=IMG . '/form/'?><?=$val['status'] == 1 ? 'active' : 'deact'?>.png" />
                    <?if(models_helpers_Access::checkAccess('change_status')):?>
                    </a>
                    <?endif;?>
                </td>
                <td><?=$val['price']?></td>
                <td><?=$val['vendor']?></td>
                <td><?=$val['cat']?></td>
                <td><?=$val['language']?></td>
                <td><?=$val['author']?></td>
                <td><?=$val['date']?></td>
            </tr>
        <?endforeach;?>
        <?endif;?>
        </tbody>
    </table> 
</form>
<?php echo $this->pagesTotal['cnt'] > 1 ? models_helpers_Paging::instance()->getPaging( $this->filter->getLinkListing(), $this->pagesTotal['cnt'], $this->filter->getPageCurrent() ): '';?>
</div>