<link href="<?=CSS?>/filters.css" rel="stylesheet" />
<?if(!empty($this->options)):?>
    <?foreach($this->options as $v):?>
        <?if($v[0]->half == 1):?>
        <?if($half_counter == 0):?>
        <div class="filter-wrapper">
        <?endif;?>
        <?$half_counter++;?>
        <?endif;?>
        <?require('options/'. $v[0]->type .'.phtml')?>
        <?$options .= '"'.$v[0]->type.'-'.$v[0]->id.'",';?>
        <?if($v[0]->half == 1 && $half_counter == 2):?>
        </div>
        <?$half_counter = 0;?>
        <?endif;?>
    <?endforeach?>
<?endif;?>