
<table class="table table-striped small">
    <thead>
    <tr>
        <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_logo']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_type']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_category']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_price']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_discount']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['product_form_radio_order']?></th>
        <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_action']?></th>
    </tr>
    </thead>
    <tbody>
    <?if(!empty($this->productTypes)):?>
    <? foreach ($this->productTypes as $val):?>
            <tr class="success">
                <td align="center"><?if($val['image']):?><img src="<?=$val['image']?>" width="50" alt="N/A"><?endif;?></td>
                <td align="center"><b><?=$val['fashion_name']?></b></td>
                <td align="center"><?=$val['category']?></td>
                <td align="center"><?=$val['price']?></td>
                <td align="center" style="vertical-align: middle;"><?=$val['discount']?></td>
                <td align="center" style="vertical-align: middle;"><?=$val['order']?></td>
                <td align="center" style="vertical-align: middle;"><a style="cursor: pointer;" data-id="<?=$val['id']?>" class="moddel"><?=$this->moduleLanguage['product_form_delete']?></a></td>
            </tr>
    <?endforeach;?>
    <?endif;?>
    </tbody>
</table>
<div class="loading"></div>
<script type="text/javascript">
    $(document).ready(function()
    {
        $('a.moddel').click(function()
        {
            var id = $(this).data('id');

            $('div.loading').css('display', 'block');
            $.ajax({
                url: BASE_URL + '/product/deleteOption/' + id,
                type: "POST",

                complete: function()
                {
                    getOptions();
                },
                dataType: 'html'

            });
        });
    });

</script>