<?if($this->basicImages):?>
    <?foreach($this->basicImages as $val):?>
        <?if($this->optionImages):?>
            <?foreach($this->optionImages as $v):?>
                <?$match = strpos($v['smallimg'], substr($val['smallimg'], 0, strpos($val['smallimg'],'.')).$this->optionName);?>
                <?if($match !== false) $val['smallimg'] = $v['smallimg']?>
            <?endforeach;?>
        <?endif;?>
<div class="col-md-2 options-preview">
    <?$newName = substr($val['smallimg'], strripos($val['smallimg'],'/')+1, 10).$this->optionName?>
    <img width="100%" src="<?=models_helpers_Url::getDomain() == '/' ? '' : models_helpers_Url::getDomain();?><?=$val['smallimg']?>?<?=md5(time())?>"/>
    <?if($this->optionName):?>
    <input type="file" name="img" id="file-<?=$newName?>" data-pk="<?=$newName?>" class="inputfile inputfile-5" />
	<label for="file-<?=$newName?>">
        <figure>
            <svg xmlns="http://www.w3.org/2000/svg" width="50%" height="17" viewBox="0 0 20 17">
                <path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/>
            </svg>
        </figure> 
        <span></span>
    </label>
    <?endif;?> 
</div>
    <?endforeach;?>
<?endif;?>  
<div class="loading-images"></div>
<script type="text/javascript">
$(document).ready(function()
{
    $('.inputfile').each(function()
	{   
        // checking all inputs with uploads
		var $input	 = $(this),
			$label	 = $(this).next('label'),
			labelVal = $label.html();
        
        // on change uploads new file
		$input.on('change', function(e)
		{
            var fileName = e.target.value.split('\\').pop();
            // if filename exists - system uploads
            if(fileName)
            {
                $('div.loading-images').css('display', 'block');
                
                var data = new FormData();
                // allow form data
                data.append('img', $(this).prop('files')[0]);
                data.append('filename', $(this).data('pk'));

                $.ajax({
                    type: "POST",
                    processData: false,
                    contentType: false,
                    data: data,
                    url: BASE_URL + '/product/addImage/'  + id,
                    success: function(data)
                    {
                        if(data)
                            alert(data);
                        getOptionsImages(opts);
                    },
                    dataType: 'html'
                });   
            }	
            else
            	$label.html(labelVal);
		});

		// Firefox bug fix
		$input
		.on('focus', function(){$input.addClass('has-focus');})
		.on('blur', function(){$input.removeClass('has-focus');});
	});
});
</script>