<?$this->options = unserialize($this->options['options_array']);?>
<table class="table table-striped small">
  <thead>
    <tr>
      <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_option']?></th>
      <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_order']?></th>
      <th style="text-align:center;"><?=$this->moduleLanguage['product_form_option_action']?></th>
    </tr>
  </thead>
  <tbody>
  <?if(!empty($this->options)):?>
  <?foreach($this->options as $key=>$val):?>
    <tr>
      <td align="center"><?=$this->model->getOptionName($val['option'])?></td>
      <td align="center"><b><?=$val['order']?></b></td>
      <td align="center" style="vertical-align: middle;"><a style="cursor: pointer;" data-pk="<?=$key?>" class="moddel"><?=$this->moduleLanguage['product_form_delete']?></a></td>
    </tr>
    <?endforeach;?>
    <?endif;?>
  </tbody>
</table>
<div class="loading-options"></div>
<script type="text/javascript">
$(document).ready(function()
{
    $('a.moddel').click(function()
    {
        var key = $(this).data('pk');

        $('div.loading-options').css('display', 'block');
        $.ajax({
            url: BASE_URL + '/product/deleteOption/' + id,
            type: "POST",
            data: {data:key},
            complete: function()
            {
                getOptions();
                renderOptions();
                getOptionsImages();
            },
            dataType: 'html'
        });
    });
});
</script>