<?if(!empty($this->sizes)):?>
<h4><?=$this->options ? $this->moduleLanguage['product_form_quant_heading'] : $this->moduleLanguage['product_form_quant_summ']?></h4>
<table class="table table-striped small sizes-table">
    <thead>
    <tr>
        <th></th>
        <?foreach ($this->sizes as $head):?>
            <th><?=$head['size']?></th>
        <?endforeach;?>
    </tr>
    </thead>
    <tbody>
        <tr class="success">
            <td><b><?=$this->moduleLanguage['product_form_sizes_quantity']?></b></td>
            <?foreach ($this->sizes as $val):?>
            <td class="editable" data-size-id="<?=$val['id']?>" data-params="<?=$this->options?>"><?=$this->quantities[$val['id']]?></td>
            <?endforeach;?>
        </tr>
    </tbody>
</table>
<?endif;?>
<div class="loading"></div>
<script type="text/javascript">
$(document).ready(function() {
    var id = <?=$this->id?>;

    $('.sizes-table td.editable').dblclick(function (e) {
        //get clicked element
        var t = e.target || e.srcElement;
        //getting tag name
        var elm_name = t.tagName.toLowerCase();
        // false if input
        if (elm_name == 'input') {
            return false;
        }
        //getting value
        var val = $(this).html().replace(/[^0-9\.]/g, '');
        var sizeId = $(this).data('size-id');
        var params = $(this).data('params');

        // 2 types of input
        var code = '<input type="text" id="edit" value="' + val + '" />';
        $(this).empty().html(code);
        $('#edit, textarea').focus();

        // action save
        $('#edit, textarea').blur(function () {
            // getting values
            var object = $(this);
            var data = new FormData();
            data.append('size_id', sizeId);
            data.append('params', params);
            data.append('value', $(this).val());
            // final action on AJAX success
            $.ajax({
                type: 'POST',
                processData: false,
                contentType: false,
                data: data,
                url: BASE_URL + '/product/changeValue/' + id,
                success: function (jsonData) {
                    object.parent().empty().html(jsonData);
                }
            });
            return false;
        });
    });
})
</script>