<div class="col-md-7 buttons">
    <a class="btn btn-primary save" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['users_save']?></a>
    <a class="btn btn-success save-exit" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['users_save_and_exit']?></a>
    <a class="btn btn-success save-add" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['users_save_and_create']?></a>
    <a class="btn btn-danger  exit" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'users/';?>"><?=$this->moduleLanguage['users_exit']?></a>
</div>
<div class="content-block col-md-12 top-marg">
    <form name="editForm" method="POST">
    <input type="hidden" name="action" value="<?=Request::instance()->getAction();?>">
    <input type="hidden" name="reg_date" value="<?=date('Y-m-d H:i:s');?>">
        <div class="col-md-5">
            <div class="form-group">
                <label><?=$this->moduleLanguage['users_form_name']?></label>
                <input type="text" name="name" class="form-control" value="<?=$this->data->_name?>" placeholder="<?=$this->moduleLanguage['users_form_name_placeholder']?>">
            </div>
            <div class="form-group">
                <label><?=$this->moduleLanguage['users_form_email']?></label>
                <input type="text" name="login" class="form-control" value="<?=$this->data->_login?>" placeholder="<?=$this->moduleLanguage['users_form_email_placeholder']?>">
            </div> 
            <div class="form-group">
                <label><?=$this->moduleLanguage['users_form_passw']?></label>
                <input type="text" autocomplete="off" name="passw" class="form-control" placeholder="<?=$this->moduleLanguage['users_form_passw_placeholder']?>">
            </div> 
            <div class="form-group">
                <label><?=$this->moduleLanguage['users_form_passw_repeate']?></label>
                <input type="text" autocomplete="off" name="cpassw" class="form-control" placeholder="<?=$this->moduleLanguage['users_form_passw_repeate_placeholder']?>">
            </div>     
        </div>
        <div class="col-md-6 col-md-offset-1">
            <div class="form-group">
                <label><?=$this->moduleLanguage['users_form_user_type']?></label>
                <select size="10" name="user_types_id" class="form-control">
                    <?=models_helpers_Options::basicOptions(models_helpers_Options::getUsersGroups(),$this->data->_types)?>
                </select>
            </div>
            <div class="form-group">
                <label><?=$this->moduleLanguage['users_form_salt']?></label>
                <input type="text" name="salt" class="form-control" value="<?=$this->data->_salt?>" placeholder="<?=$this->moduleLanguage['users_form_salt']?>">
            </div>  
        </div>
    </form>
</div>