<?php $filters = $this->filter->getData(); ?>
<form class="col-md-7 search-block" id="filter" action="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkForm()?>" method="post" onsubmit="return PathGenerator(this);">
    <div class="col-md-3">
        <select class="form-control" name="status"><?=models_helpers_Options::basicOptions(models_helpers_Options::statuses(), @$filters['status'], 0, $this->moduleLanguage['users_search_status'])?></select>
    </div>
    <div class="col-md-4">
        <select class="form-control" name="users_group"><?=models_helpers_Options::basicOptions(models_helpers_Options::getUsersGroups(), @$filters['users_group'], 0, $this->moduleLanguage['users_search_group'])?></select>
    </div>
    <div class="col-md-4">
        <div class="input-group">
            <input type="text" name="fulltext" value="<?=@$filters['fulltext']?>" class="form-control" placeholder="<?=$this->moduleLanguage['users_search_text']?>"/>
            <span class="input-group-btn">
            <input type="submit" class="btn btn-default" value="<?=$this->moduleLanguage['users_search_button']?>"/>
            </span>
        </div>    
    </div>
    <div class="col-md-1">
        <a href="#" class="clearSrch"><img src="<?=IMG?>/form/reset.png" title="<?=$this->moduleLanguage['users_search_reset']?>"/></a>
    </div>
</form>
<div class="col-md-5 buttons">
    <?if(models_helpers_Access::checkAccess('add')):?>
    <a class="btn btn-primary add" href="<?php echo models_helpers_Url::getValidBaseUrl().'users/add';?>"><?=$this->moduleLanguage['users_create']?></a>
    <?endif;?>
    <?if(models_helpers_Access::checkAccess('change_status')):?>
    <a class="btn btn-success activate" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'users/';?>"><?=$this->moduleLanguage['users_activation']?></a>
    <a class="btn btn-warning deactivate" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'users/';?>"><?=$this->moduleLanguage['users_deactivation']?></a>
    <a class="btn btn-danger  delete" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'users/';?>"><?=$this->moduleLanguage['users_delete']?></a>
    <?endif;?>
</div>
<div class="maincontent center-block">
<form method="post" name="baseform">
    <table class="table table-striped table-hover small">
        <thead>
            <tr>
                <th><input type="checkbox" class="dl" name="select_all" title="<?=$this->moduleLanguage['users_table_check_all']?>"></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('id') ?>" class="<?php echo $this->filter->checkSortOrder('id') ?>"><?=$this->moduleLanguage['users_table_id']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('name') ?>" class="<?php echo $this->filter->checkSortOrder('name') ?>"><?=$this->moduleLanguage['users_table_user_name']?></a></th>
                <th><?=$this->moduleLanguage['users_search_status']?></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('users_group') ?>" class="<?php echo $this->filter->checkSortOrder('users_group') ?>"><?=$this->moduleLanguage['users_search_group']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('reg_date') ?>" class="<?php echo $this->filter->checkSortOrder('reg_date') ?>"><?=$this->moduleLanguage['users_table_registration']?></a></th> 
            </tr>
        </thead>
        <tbody>
        <?foreach($this->datalist as $key => $val):?>
            <tr>
                <td><input class="il" type="checkbox" name="dellist[]" value="<?=$val['id']?>"/></td>
                <th><?=$val['id']?></th>
                <td>
                    <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
                    <a href="<?=models_helpers_Url::getValidBaseUrl().'users/edit/'.$val['id']?>">
                    <?endif;?>
                    <?=$val['name']?>
                    <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
                    </a>
                    <?endif;?>
                </td>
                <td>
                    <?if(models_helpers_Access::checkAccess('change_status')):?>
                    <a href="<?=models_helpers_Url::getValidBaseUrl().'users/changeStatus/'.$val['id']?>">
                    <?endif;?>
                    <img src="<?=IMG . '/form/'?><?=$val['status'] == 1 ? 'active' : 'deact'?>.png" />
                    <?if(models_helpers_Access::checkAccess('change_status')):?>
                    </a>
                    <?endif;?>
                </td>
                <td><?=$val['users_group']?></td>
                <td><?=$val['reg_date']?></td>
            </tr>
        <?endforeach;?>
        </tbody>
    </table> 
</form>
<?php echo $this->pagesTotal['cnt'] > 1 ? models_helpers_Paging::instance()->getPaging( $this->filter->getLinkListing(), $this->pagesTotal['cnt'], $this->filter->getPageCurrent() ): '';?>
</div>