<div class="container">
    <div class="row">
        <div class="auth_title">
            <a href="/account/account">
                <?=(isset($_SESSION['default']['name'])) ? $this->moduleLanguage['my_acc'] : $this->moduleLanguage['authorization'] ?></a>
            <a href="/account/logout">
                <?if (isset ($_SESSION['default']['name'])) echo $this->moduleLanguage['logout'];?></a>
        </div>
    </div> <!--row-->
    <?foreach ($this->productInfo as $product):?>
        <div class="row">
            <div class="col-md-2">
                <img src="<?=$product['product_image']?>" class="product" alt="N/A">
            </div>
            <div class="col-md-6">
                <p><?=$product['product_name']?></p>
                <p><?=$this->moduleLanguage['product_price']?>: <?=$product['price']?>$</p>
                <p><?=$this->moduleLanguage['product_discount']?>: <?=$product['discount']?>$</p>
                <p><?=$this->moduleLanguage['product_newprice']?>: <?=$product['new_price']?>$</p>
                <p><?=$this->moduleLanguage['product_size']?>: <?=$product['size']?></p>
                <a href="/cart" class="btn btn-custom-xs product"><?=$this->moduleLanguage['product_add_cart']?></a>
            </div>
        </div><!-- row -->
    <?endforeach;?>
</div> <!-- container -->