<div class="container">
    <?foreach ($this->productInfo as $product):?>
        <div class="row">
            <div class="col-md-2">
                <img src="<?=$product['product_image']?>" class="product" alt="N/A">
            </div>
            <div class="col-md-6">
                <p><?=$product['product_name']?></p>
                <p><?=$this->moduleLanguage['product_price']?>: <?=$product['price']?>$</p>
                <p><?=$this->moduleLanguage['product_discount']?>: <?=$product['discount']?>$</p>
                <p><?=$this->moduleLanguage['product_newprice']?>: <?=$product['new_price']?>$</p>
                <p><?=$this->moduleLanguage['product_size']?>: <?=$product['size']?></p>
                <a href="/cart" class="btn btn-custom-xs product"><?=$this->moduleLanguage['product_add_cart']?></a>
            </div>
        </div><!-- row -->
    <?endforeach;?>
</div> <!-- container -->