<?$slider = unserialize($v[0]->options_array)?>
<div class="width-filter-wrapper">
	<div class="filter-title">
		<h3><?=$v[0]->name?></h3>
	</div>
	<img src="<?=$v[0]->image?>" alt="<?=$v[0]->name?>">
	<span name="option-min-<?=$v[0]->id?>" class="depth-val" id="width-filter-min"></span>
	<div name="option-<?=$v[0]->id?>" id="width-filter"></div>
	<span name="option-max-<?=$v[0]->id?>" class="depth-val" id="width-filter-max"></span>
</div>
<noindex>
<script>
// define vars
var skipSlider<?=$v[0]->id?> = document.getElementsByName('option-<?=$v[0]->id?>')[0];
var step<?=$v[0]->id?>     = <?=$slider['step']?>;
var multiply<?=$v[0]->id?> = <?=$slider['multiply']?>;
var min<?=$v[0]->id?>      = <?=$slider['min']?>;
var max<?=$v[0]->id?>      = <?=$slider['max']?>;
var priceMultiply<?=$v[0]->id?>;

// settingslider options
noUiSlider.create(skipSlider<?=$v[0]->id?>, 
{
	start: [min<?=$v[0]->id?>, max<?=$v[0]->id?>],
    step: step<?=$v[0]->id?>,
	connect: true,
	mark:false,
	range: {
		min: min<?=$v[0]->id?>,
		max: max<?=$v[0]->id?>
	},
	format: wNumb({decimals: <?=$slider['step']%1 == 0 ? 1 : 0?>})
});

$(document).ready(function()
{   
    // slider values
    var skipValues = [
    	document.getElementsByName('option-min-<?=$v[0]->id?>')[0],
    	document.getElementsByName('option-max-<?=$v[0]->id?>')[0]
    ];
    
    // event on change
    skipSlider<?=$v[0]->id?>.noUiSlider.on('update', function( values, handle ) 
    {            
        // calculating new price 
        priceMultiply<?=$v[0]->id?> = Math.pow(multiply<?=$v[0]->id?>,((values[0]-min<?=$v[0]->id?>)+(max<?=$v[0]->id?>-values[1]))/step<?=$v[0]->id?>);
        // change values in HTML
    	skipValues[handle].innerHTML = values[handle];
    });
});
</script>	
</noindex>