<?$radio = unserialize($v[0]->options_array)?>
<div class="row item-form diametr">
	<div class="filter-title">
		<h3><?=$v[0]->name?></h3>
	</div>
	<img src="<?=$v[0]->image?>" alt="<?=$v[0]->name?>">
    <?foreach($radio as $sv):?>
	<div class="choose-diametr">
		<input class="d_button" <?=reset($radio) === $sv ? 'checked' : ''?> type="radio" name="option-<?=$v[0]->id?>" value="<?=$sv['order']?>" id="<?=$v[0]->id?>-<?=$sv['order']?>" data-pk="<?=$sv['multiply']?>">
		<label for="<?=$v[0]->id?>-<?=$sv['order']?>">
            <span class="choose-diametr-size"><?=$sv['val']?></span>
        </label>
	</div>
    <?endforeach;?>	
</div><!-- radio-->
<noindex>
<script>

// function changing slider value and price
$("input:radio[name='option-<?=$v[0]->id?>']").on('click', function()  
{
    //loading bar
    $('div.loading-images').css('display', 'block');
    // adding option value to array
    opts[<?=$v[0]->id?>] = $(this).val();
    // no extra images if basic options selected
    //checkBase();
    // getting images    
    getSizes(opts);
    getOptionsImages(opts);
});
</script>
</noindex>