<link href="<?=CSSPATH?>chosen.css" rel="stylesheet">
<script src="<?=JSPATH?>chosen.jquery.js"></script>
<script>
$(function(){   
    $(".chosen-select-<?=$v[0]->id?>").chosen();
});
</script>
<?$select = unserialize($v[0]->options_array)?>
<div class="row item-form diametr">
	<div class="filter-title">
		<h3><?=$v[0]->name?></h3>
	</div>
	<img src="<?=$v[0]->image?>" alt="<?=$v[0]->name?>">
    <select class="chosen-select-<?=$v[0]->id?>">
    <?foreach($select as $sv):?>  
        <option value="<?=$sv['multiply']?>"><b><?=$sv['order']?></b> — <?=$sv['val']?></option>
    <?endforeach;?>
    </select>	
</div><!-- select-->