<?$slider = unserialize($v[0]->options_array)?>
<div class="depth-filter-wrapper">
	<div class="filter-title">
		<h3><?=$v[0]->name?></h3>
	</div>
	<img src="<?=$v[0]->image?>" alt="<?=$v[0]->name?>">
	<div name="slider-<?=$v[0]->id?>" id="depth-filter"></div>
	<input name="option-<?=$v[0]->id?>" type="text" id="depth-filter-size" readonly style="border: none; ">
</div>
<noindex>
<script>
// define vars
var keypressSlider<?=$v[0]->id?> = document.getElementsByName('slider-<?=$v[0]->id?>')[0],
	input<?=$v[0]->id?> = document.getElementsByName('option-<?=$v[0]->id?>')[0];   
var step<?=$v[0]->id?>     = <?=$slider['step']?>;
var multiply<?=$v[0]->id?> = <?=$slider['multiply']?>;
var min<?=$v[0]->id?>      = <?=$slider['min']?>;
var priceMultiply<?=$v[0]->id?>;

// settingslider options
noUiSlider.create(keypressSlider<?=$v[0]->id?>, 
{
	start: min<?=$v[0]->id?>,
    step: step<?=$v[0]->id?>,
    format: wNumb({decimals: <?=$slider['step']%1 == 0 ? 1 : 0?>}),
	range: {
		'min': min<?=$v[0]->id?>,
		'max': <?=$slider['max']?>
	}
});

$(document).ready(function()
{     
    // function changing slider value and price
    keypressSlider<?=$v[0]->id?>.noUiSlider.on('update', function( values, handle ) 
    {           
        // calculating new price 
        priceMultiply<?=$v[0]->id?> = Math.pow(multiply<?=$v[0]->id?>,(values-min<?=$v[0]->id?>)/step<?=$v[0]->id?>);
    	// change values in HTML
        input<?=$v[0]->id?>.value = values[handle];
    });
    
    // event on change
    input<?=$v[0]->id?>.addEventListener('change', function()
    {
    	keypressSlider.noUiSlider.set([null, this.value]);
    });
});
</script>
</noindex>