<?if($this->sizes):?>
<?foreach ($this->sizes as $key=>$val):?>
<div class="col-md-6">
    <h4><?=$this->names[$key]?></h4>
    <a href="#" data-pk="<?=$val[0]['id']?>" class="delete-size">×</a>
    <table class="table table-striped small sizes-table">
        <thead>
        <tr>
            <th><?=$this->moduleLanguage['suppliers_form_sizes_types']?></th>
            <?foreach ($val as $k=>$v):?>
            <?if($size != $v['size']):?>
            <?$size = empty($size) || $size != $v['size'] ? $v['size'] : $size;?>
            <th><?=$size?></th>
            <?endif;?>
            <?endforeach;?>
        </tr>
        </thead>
        <tbody>
        <?foreach($val as $k=>$v):?>
        <?if($size == $v['size']):?>
        <?$size = empty($size) ? $v['size'] : $size;?>
        <?$option = $v['option_id']?>
            <tr>
                <td><?=$v['size_option']?></td>
                <?foreach ($val as $k=>$v):?>
                <?if($size != $v['size']):?>
                <?$size = empty($size) || $size != $v['size'] ? $v['size'] : $size;?>
                <td data-size="<?=$v['size_id']?>" data-option="<?=$option?>" data-pack="<?=$v['id']?>" class="editable">
                    <?if($this->values):?>
                    <?foreach ($this->values as $value):?>
                    <?if($value["size_id"] == $v['size_id'] && $value["size_option_id"] == $option):?>
                    <?=$value['value'];?>
                    <?endif;?>
                    <?endforeach;?>
                    <?endif;?>
                </td>
                <?endif;?>
                <?endforeach;?>
            </tr>
        <?endif;?>
        <?endforeach;?>
        </tbody>
    </table>
</div>
<?endforeach;?>
<?endif;?>
<div class="loading sizes"></div>
<script type="text/javascript">
    $(document).ready(function()
    {
        var id = <?=$this->id?>;

        $('.sizes-table td.editable').dblclick(function(e)
        {
            //get clicked element
            var t = e.target || e.srcElement;
            //getting tag name
            var elm_name = t.tagName.toLowerCase();
            // false if input
            if(elm_name == 'input')	{return false;}
            //getting value
            var val     = $(this).html().replace(/[^0-9\.]/g, '');
            var size    = $(this).data('size');
            var pack    = $(this).data('pack');
            var option  = $(this).data('option');

            // 2 types of input
            var code ='<input type="text" id="edit" value="'+val+'" />';
            $(this).empty().html(code);
            $('#edit, textarea').focus();

            // action save
            $('#edit, textarea').blur(function()
            {
                // getting values
                var object = $(this);
                var data = new FormData();
                data.append('size', size);
                data.append('pack', pack);
                data.append('option', option);
                data.append('value', $(this).val());
                // final action on AJAX success
                $.ajax({
                    type: 'POST',
                    processData: false,
                    contentType: false,
                    data: data,
                    url: BASE_URL + '/suppliers/changeValue/' + id,
                    success: function(jsonData)
                    {
                        object.parent().empty().html(jsonData);
                    }
                });
                return false;
            });
        });

        $('.delete-size').click(function()
        {
            del_id = $(this).data('pk');

            if (window.confirm("<?=$this->moduleLanguage['suppliers_form_delete_size']?>"))
            {
                $('div.loading.sizes').css('display', 'block');
                $.ajax({
                    url: BASE_URL + '/suppliers/deleteSize/' + del_id,
                    success: function(jsonData)
                    {
                        if(jsonData)
                            alert(jsonData);

                        $('div.loading.sizes').css('display', 'none');
                        getSizes();
                    },
                    dataType: 'html'
                });
            }

        });
    });
</script>