<link href="<?=CSS?>/chosen.css" rel="stylesheet">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<script src="<?=JS?>/chosen.jquery.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="<?=JS?>/datepicker/<?=models_helpers_Url::getConfigLanguage()?>.js"></script>
<script src="<?=JS?>/orders.js"></script>
<script> 
$(function()
{
    $(".chosen-select").chosen();
    $.datepicker.regional["<?=models_helpers_Url::getConfigLanguage()?>"];
    $( "#date_from" ).datepicker({maxDate: "+ 0D",dateFormat: "yy-mm-dd",changeMonth: true,changeYear: true});
    $( "#date_before" ).datepicker({maxDate: "+ 1D",dateFormat: "yy-mm-dd",changeMonth: true,changeYear: true});
});
</script>

<?php $filters = $this->filter->getData(); ?>
<?php $date    = $this->filter->getDateFilter();?>
<form class="col-md-12 search-block" id="filter" action="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkForm()?>" method="post" onsubmit="return PathGenerator(this);">
    <div class="col-md-2">
        <select class="form-control" name="status"><?=models_helpers_Options::basicOptions(models_helpers_Options::OrderStatuses(), @$filters['status'], 0, $this->moduleLanguage['order_search_status'])?></select>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <input type="text" class="form-control" value="<?=$date ? $date[0] : '' ?>" name="dtfrom" id="date_from" placeholder="<?=$this->moduleLanguage['certificate_search_date_from']?>"/>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <input type="text" class="form-control" value="<?=$date ? $date[1] : '' ?>" name="dtbefore" id="date_before" placeholder="<?=$this->moduleLanguage['certificate_search_date_before']?>"/>
        </div>
    </div>
    <div class="col-md-3">
        <div class="input-group">
            <input type="text" name="fulltext" value="<?=@$filters['fulltext']?>" class="form-control" placeholder="<?=$this->moduleLanguage['order_search_text']?>"/>
            <span class="input-group-btn">
            <input type="submit" class="btn btn-default" value="<?=$this->moduleLanguage['order_search_button']?>"/>
            </span>
        </div>
    </div>
    <div class="col-md-1">
        <a href="#" class="clearSrch"><img src="<?=IMG?>/form/reset.png" title="<?=$this->moduleLanguage['order_search_reset']?>"/></a>
    </div>
</form>
<div class="maincontent center-block">
<form method="post" name="baseform">
    <table class="table table-hover small orders">
        <thead>
            <tr>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('id') ?>" class="<?php echo $this->filter->checkSortOrder('id') ?>"><?=$this->moduleLanguage['order_table_id']?></a></th>
                <!--<th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('country') ?>" class="<?php echo $this->filter->checkSortOrder('country')?>"><?=$this->moduleLanguage['order_table_country']?></a></th>-->
                <th><?=$this->moduleLanguage['order_table_address']?></th>
                <th><?=$this->moduleLanguage['order_table_customer']?></th>
                <th><?=$this->moduleLanguage['order_table_phone']?></th>
                <th><?=$this->moduleLanguage['order_table_email']?></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('date_add') ?>" class="<?php echo $this->filter->checkSortOrder('date_add')?>"><?=$this->moduleLanguage['order_table_date']?></a></th>
                <th><?=$this->moduleLanguage['order_table_comment']?></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('price') ?>" class="<?php echo $this->filter->checkSortOrder('price')?>"><?=$this->moduleLanguage['order_table_price']?></a></th>      
                <th style="min-width: 120px"><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('status') ?>" class="<?php echo $this->filter->checkSortOrder('status')?>"><?=$this->moduleLanguage['order_table_status']?></a></th>
            </tr>
        </thead>
        <tbody>
        <?if($this->datalist):?>
        <?foreach($this->datalist as $key => $val):?>
            <tr class="<?=models_helpers_Options::$statusColors[$val['status']]?>">
                <td><?=$val['id']?></td>
                <td class="middle-size"><i data-db="clients_address-address" data-type="input" data-id="<?=$val['t5id']?>"><?=$val['address']?></i></td>
                <td class="middle-size"><a target="_blank" href="<?=models_helpers_Url::getValidBaseUrl()?>clients/edit/<?=$val['t2id']?>"><?=$val['first_name']?> <?=$val['last_name']?></a></td>
                <td class="middle-size"><b><i data-db="clients_phones-phone" data-type="input" data-id="<?=$val['t3id']?>"><?=$val['phone']?></i></b></td>
                <td><i data-db="clients_emails-email" data-type="input" data-id="<?=$val['t4id']?>"><?=$val['email']?></i></td>
                <td><?=$val['date_add']?></td>
                <td><?=$val['comment']?></td>
                <td><i data-db="orders-price" data-type="input" data-id="<?=$val['id']?>"><?=$val['total_price']?></i></td>
                <td>
                    <i data-db="orders-status" data-type="select" data-id="<?=$val['id']?>">
                        <?=models_helpers_Options::OrderStatuses($val['status'])?>
                    </i>
                    <select name="status" id="edit">
                        <?=models_helpers_Options::basicOptions(models_helpers_Options::OrderStatuses(), $val['status'], 0, $this->moduleLanguage['order_search_status'])?>
                    </select>
                </td>
            </tr>
            <?if($val['orderItems']):?>
            <?foreach($val['orderItems'] as $k => $v):?>
            <tr class="<?=models_helpers_Options::$statusColors[$v['status']]?>">
                <td></td>
                <td><img src="<?=$v['image']?>" width="30"/></td>
                <td><?if(!$v['name']):?><a href="/<?=$v['url']?>"><?=$v['productname']?></a><?else:?><?=$v['name']?><?endif;?></td>
                <?$opts = unserialize(html_entity_decode($v['options']));?>
                <td colspan="3">
                    <?if($opts):?>
                    <?foreach($opts as $i=>$o):?>
                    <?$opt = explode('-',$i)[1];?>
                    <i data-db="order_items-options" data-type="select" data-id="<?=$v['id']?>" data-option="<?=$i?>">
                        <?=$this->options[$opt][$o]['val']?>
                    </i>
                    <select id="edit" class="<?=$i?>" style="max-width:100px">
                        <?=models_helpers_Options::productOptions($this->options[$opt], $o, 0, $this->moduleLanguage['order_search_status'],$o)?>
                    </select>
                    <?endforeach;?>
                    <?endif;?>
                </td>
                <td></td>
                <td><i data-db="order_items-price" data-type="input" data-id="<?=$v['id']?>"><?=$v['price']?></i></td>
                <td></td>
            </tr>
            <?endforeach;?>
            <?endif;?>
        <?endforeach;?>
        <?endif;?>
        </tbody>
    </table> 
</form>
<?php echo $this->pagesTotal['cnt'] > 1 ? models_helpers_Paging::instance()->getPaging( $this->filter->getLinkListing(), $this->pagesTotal['cnt'], $this->filter->getPageCurrent() ): '';?>
</div>