<link href="<?=CSS?>/bootstrap-switch.css" rel="stylesheet">
<link href="<?=CSS?>/chosen.css" rel="stylesheet">

<script src="<?=JS?>/chosen.jquery.js"></script>
<script src="<?=JS?>/highlight.js"></script>
<script src="<?=JS?>/bootstrap-switch.js"></script>
<script src="<?=JS?>/main.js"></script>
<script src="<?=JS?>/ckeditor/ckeditor.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.5/angular.min.js"></script>
<script type="text/javascript" src="<?=JS?>/angular/content/app.js"></script>
<script type="text/javascript" src="<?=JS?>/angular/content/controllers.js"></script>
<script type="text/javascript" src="<?=JS?>/angular/content/services.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.5/angular-resource.js"></script>

<script type="text/javascript">
$(function() {
    $(".chosen-select").chosen({allow_single_deselect: true});
});
</script>

<div class="col-md-7 buttons">
    <a class="btn btn-primary save" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['content_save']?></a>
    <a class="btn btn-success save-exit" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['content_save_and_exit']?></a>
    <a class="btn btn-success save-add" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['content_save_and_create']?></a>
    <a class="btn btn-danger  exit" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'content/';?>"><?=$this->moduleLanguage['content_exit']?></a>
</div>
<div class="content-block col-md-12">
    <form name="editForm" method="POST" ng-app="contentModule">
        <input type="hidden" name="author" value="<?=$this->data->_author ? $this->data->_author : $this->userInfo['id'];?>">
        <input type="hidden" name="action" value="<?=Request::instance()->getAction();?>">
        <input type="hidden" name="params" value="<?if($this->params)foreach($this->params as $key => $val):echo $val['id']."|";endforeach;?>">
        <input type="hidden" name="langs"  value="<?if($this->langs)foreach($this->langs  as $key => $val):echo $val['short_name']."|";endforeach;?>">
        <div class="tabs">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab-1" data-toggle="tab"><?=$this->moduleLanguage['content_form_tab1']?></a></li>
                <li><a href="#tab-2" data-toggle="tab"><?=$this->moduleLanguage['content_form_tab2']?></a></li>
                <li><a href="#tab-3" data-toggle="tab"><?=$this->moduleLanguage['content_form_tab3']?></a></li>
                <li><a href="#tab-4" data-toggle="tab"><?=$this->moduleLanguage['content_form_tab4']?></a></li>
                <li><a href="#tab-5" data-toggle="tab"><?=$this->moduleLanguage['content_form_tab5']?></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab-1">
                    <div class="col-md-6">   
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_name']?></label>
                            <input type="text" name="name" class="form-control" value="<?=$this->data->_name?>" placeholder="<?=$this->moduleLanguage['content_form_name_placeholder']?>">
                        </div>
                        <div class="col-md-7 radio-switch">
                            <div class="form-group">
                                <label><?=$this->moduleLanguage['content_form_hide_name']?></label>
                                <input type="radio" name="show_title" <?=$this->data->_show_title == 1 ? 'checked' : ''?> data-radio-all-off="true"  class="switch-radio">
                            </div>
                            <div class="form-group">
                                <label><?=$this->moduleLanguage['content_form_show_date']?></label>
                                <input type="radio" name="show_date" <?=$this->data->_show_date == 1 ? 'checked' : ''?> data-radio-all-off="true"  class="switch-radio">
                            </div>
                            <div class="form-group">
                                <label><?=$this->moduleLanguage['content_form_show_comments']?></label>
                                <input type="radio" name="showCmnt" <?=$this->data->_showCmnt == 1 ? 'checked' : ''?> data-radio-all-off="true"  class="switch-radio">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5 col-md-offset-1">
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_table_category']?></label>
                            <select name="category" class="form-control chosen-select">
                                <option value=""></option>
                                <?=models_helpers_Options::basicOptions(models_helpers_Options::getCategories(),$this->data->_category)?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_url']?></label>
                            <input type="text" name="url" class="form-control" value="<?=$this->data->_url?>" placeholder="<?=$this->moduleLanguage['content_form_url_placeholder']?>">
                        </div> 
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_language']?></label>
                            <select class="form-control" name="main_lang">
                                <?=models_helpers_Options::basicOptions(models_helpers_Options::getLanguage(),$this->data->_main_lang,'',$this->moduleLanguage['content_form_language_placeholder'])?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="tab-2">
                   <div class="col-md-6">   
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_title']?></label>
                            <input type="text" name="title" value="<?=$this->data->_title?>" class="form-control">
                        </div> 
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_description']?></label>
                            <textarea class="form-control" rows="5" name="description"><?=$this->data->_description?></textarea>
                        </div> 
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_keywords']?></label>
                            <input type="text" name="keywords" value="<?=$this->data->_keywords?>" class="form-control">
                        </div> 
                    </div>
                    <div class="col-md-5 col-md-offset-1 radio-switch">
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_image']?></label>
                            <input type="radio" name="cat_img" <?=$this->data->_cat_img == 1 ? 'checked' : ''?> data-radio-all-off="true"  class="switch-radio">
                        </div>
                        <?if(Request::instance()->getAction() == 'add'):?>
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_image_warning']?></label>
                        </div>
                        <?else:?>
                        <div id="images"></div>
                        <div class="form-group col-md-6">
                            <label><?=$this->moduleLanguage['content_form_image_load']?></label>
                            <input class="mrg-load" name="img" type="file">
                        </div>
                        <div class="form-group col-md-3">
                            <label><?=$this->moduleLanguage['content_form_image_main']?></label>
                            <input type="checkbox" name="main"> 
                        </div>
                        <a type="submit" class="btn btn-primary mrg-btn upload"><?=$this->moduleLanguage['content_form_image_load_button']?></a>
                        <?endif;?>
                    </div>
                </div>
                <div class="tab-pane" id="tab-3">
                    <div class="col-md-6">   
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_template']?></label>
                            <select size="10" name="template" class="form-control">
                                <?=models_helpers_Options::basicOptions(models_helpers_Options::getTemplates(),$this->data->_template)?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_contype']?></label>
                            <select class="form-control" name="contype">
                                <?=models_helpers_Options::basicOptions(models_helpers_Options::getContentType(),$this->data->_contype,'',$this->moduleLanguage['content_form_contype_placeholder'])?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_order']?></label>
                            <input type="text" name="ordr" value="<?=$this->data->_ordr?>" class="form-control">
                        </div> 
                    </div>
                    <div class="col-md-5 col-md-offset-1">
                        <?if(Request::instance()->getAction() == 'add'):?>
                        <div class="form-group">
                            <label><?=$this->moduleLanguage['content_form_other_langs_warning']?></label>
                        </div>
                        <?else:?>
                        <?if($this->langs):?>
                        <?foreach($this->langs as $key => $val):?>
                        <div class="form-group">
                            <label><?=$val['name']?></label>
                            <input type="text" name="<?=$val['short_name']?>" value="<?=$this->data->_language[$val['short_name']]?>" class="form-control">
                        </div>    
                        <?endforeach;?>
                        <?endif;?>
                        <?endif;?>
                        <?if($this->params):?>
                        <?foreach($this->params as $key => $val):?>
                        <div class="form-group">
                            <label><?=$val['name']?></label>
                            <input type="text" name="param_<?=$val['id']?>" value="<?=@$this->data->_params[$val['id']]?>" class="form-control">
                        </div>    
                        <?endforeach;?>
                        <?endif;?>
                    </div>
                </div>
                <div class="tab-pane" id="tab-4">
                    <textarea id="content" name='content'><?=$this->data->_content?></textarea>
                </div>
                <div class="tab-pane" id="tab-5">
                    <div class="form-group col-md-4">
                        <label><?=$this->moduleLanguage['content_form_brand']?></label>
                        <select class="form-control chosen-select" name="brand">
                            <?=models_helpers_Options::basicOptions(models_helpers_Options::getBrands(),$this->data->_brand,'',$this->moduleLanguage['content_brand_placeholder'])?>
                        </select>
                    </div>
                    <div class="form-group col-md-8" ng-controller="ContentModuleCtrl">
                        <label><?=$this->moduleLanguage['content_form_lookbook']?></label>
                        <div class="dropdown">
                            <input type="text" class="form-control" ng-change="showList(search)" ng-model="search" placeholder="<?=$this->moduleLanguage['content_form_lookbook_placeholder']?>" data-toggle="dropdown" aria-expanded="false">
                            <ul class="products-dropdown dropdown-menu" ng-if="productsList">
                                <li ng-cloak ng-repeat="product in productsList">
                                    <a ng-click="addProduct(product.id)">{{product.id}}. <img ng-if="product.img" src="{{product.img}}" width="30">
                                        <span>{{product.name}} - <b>{{product.brandname}}</b></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-2 look-product" ng-cloak ng-repeat="product in addedList">
                            <img src="{{product.img}}"  ng-if="product.img">
                            <span class="look_name">{{product.id}}. {{product.name}} - <b>{{product.brandname}}</b></span>
                            <a class="deleteLink" ng-click="deleteProduct(product.ident)">x</a>
                        </div>
                    </div>
                </div>
            </div>     
        </div>
    </form>
</div>

<script type="text/javascript">
var id = <?=$this->data->_id ? $this->data->_id : 0?>;

$(document).ready(function()
{
    $('a.upload').on('click', function(e)
    {
        e.preventDefault();   
        $('div.loading').css('display', 'block');
        var data = new FormData();
        // присвоение данных таблицы для отправки постом
        data.append('img', $('input[type="file"]').prop('files')[0]);
        data.append('main', $('input[type="checkbox"]').prop('checked'));
    
        $.ajax({
            type: 'POST',               
            processData: false,
            contentType: false,
            data: data,
            url: BASE_URL + '/content/uploadImage/' + id,
            success: function(jsonData)
            {
                if(jsonData)
                    alert(jsonData);
                getImages();
            }
        }); 
    });  
});

getImages();
// вызов картинок материала
function getImages()
{
    $.get(BASE_URL + '/content/getlist/' + id, null, function(data)
    {
        $('.col-md-5 #images').html(data);
    });
}

CKEDITOR.replace( 'content', {
	height: 300,
    language: '<?=models_helpers_Url::getConfigLanguage()?>',

    filebrowserImageBrowseUrl: '<?=JS?>/kcfinder/browse.php?opener=ckeditor&type=images',
    filebrowserImageUploadUrl: '<?=JS?>/kcfinder/upload.php?opener=ckeditor&type=images',
});
</script>