<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>About Me</title>
    <!-- Bootstrap -->
    <link href="<?=CSS?>jumbotron.css" rel="stylesheet">
    <link href="<?=CSS?>style.css" rel="stylesheet">
    <link href="<?=CSS?>fonts.css" rel="stylesheet">
    <link href="<?=CSS?>bootstrap.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="<?=JS?>basic.js"></script>
    <script type="text/javascript" src="<?=JS?>popper.min.js"></script>
    <script type="text/javascript" src="<?=JS?>bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/index">Главная</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Админская часть</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/account">Раздел авторизации</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/product">Сторона сайта</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/additional">Дополнительный функционал</a>
                </li>
            </ul>
        </div>
    </nav>
    <main role="main">
        <?php include $this->_template;?>
    </main>

    <footer class="container">
        <hr>
        <p>&copy; KarinaE</p>
    </footer>
</body>
</html>

