<link href="<?=CSS?>/bootstrap-switch.css" rel="stylesheet">
<link href="<?=CSS?>/chosen.css" rel="stylesheet">

<script src="<?=JS?>/chosen.jquery.js"></script>
<script src="<?=JS?>/highlight.js"></script>
<script src="<?=JS?>/bootstrap-switch.js"></script>
<script src="<?=JS?>/main.js"></script>

<script> 
$(function(){   
    $(".chosen-select").chosen();
});
</script>

<div class="col-md-7 buttons">
    <a class="btn btn-primary save" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['categories_save']?></a>
    <a class="btn btn-success save-exit" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['categories_save_and_exit']?></a>
    <a class="btn btn-success save-add" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['categories_save_and_create']?></a>
    <a class="btn btn-danger  exit" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'categories/';?>"><?=$this->moduleLanguage['categories_exit']?></a>
</div>
<div class="content-block col-md-12 top-marg">
    <form name="editForm" method="POST">
    <input type="hidden" name="author" value="<?=$this->data->_author ? $this->data->_author : $this->userInfo['id'];?>">
    <input type="hidden" name="action" value="<?=Request::instance()->getAction();?>">
        <div class="col-md-6">
            <div class="form-group">
                <label><?=$this->moduleLanguage['categories_form_name']?></label>
                <input type="text" name="name" class="form-control" value="<?=$this->data->_name?>" placeholder="<?=$this->moduleLanguage['categories_form_name_placeholder']?>">
            </div>
            <div class="form-group">
                <label><?=$this->moduleLanguage['categories_form_main']?></label>
                <input type="radio" name="main" <?=$this->data->_main == 1 ? 'checked' : ''?> data-radio-all-off="true"  class="switch-radio">
            </div> 
            <div class="form-group">
                <label><?=$this->moduleLanguage['categories_form_page']?></label>
                <input type="text" name="page" class="form-control" value="<?=$this->data->_page?>" placeholder="<?=$this->moduleLanguage['categories_form_page_placeholder']?>">
            </div>      
            <div class="form-group">
                <label><?=$this->moduleLanguage['categories_form_ordr']?></label>
                <input type="text" name="ordr" class="form-control" value="<?=$this->data->_ordr?>" placeholder="<?=$this->moduleLanguage['categories_form_ordr_placeholder']?>">
            </div> 
        </div>
        <div class="col-md-5 col-md-offset-1">
            <div class="form-group">
                <label><?=$this->moduleLanguage['categories_form_parent_id']?></label>
                <select size="10" name="parent_id" class="form-control chosen-select">
                    <?=models_helpers_Options::basicOptions(models_helpers_Options::getCategories($this->data->_category),$this->data->_parent_id,'',$this->moduleLanguage['categories_form_parent_id_placeholder'])?>
                </select>
            </div> 
            <div class="tabs">
                <label><?=$this->moduleLanguage['categories_search_group']?></label>
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab-1" data-toggle="tab"><?=$this->moduleLanguage['categories_form_group_existed']?></a></li>
                    <li><a href="#tab-2" data-toggle="tab"><?=$this->moduleLanguage['categories_form_group_new']?></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab-1">
                        <select class="form-control" name="category"><?=models_helpers_Options::basicOptions(models_helpers_Options::getCatGroups(), $this->data->_category, 0,$this->moduleLanguage['categories_form_group_pick_placeholder'])?></select>  
                    </div>
                    <div class="tab-pane" id="tab-2">
                        <input type="text" name="new_category" class="form-control" placeholder="<?=$this->moduleLanguage['categories_form_group_new_placeholder']?>">
                    </div>
                </div>     
            </div>
        </div>
    </form>
</div>