<table class="table table-striped small">
  <thead>
    <tr>
      <th style="text-align:center;"><?=$this->moduleLanguage['configs_lang_flag']?></th>
      <th style="text-align:center;"><?=$this->moduleLanguage['configs_lang_lang']?></th>
      <th style="text-align:center;"><?=$this->moduleLanguage['configs_lang_abbreviation']?></th>
      <th style="text-align:center;"><?=$this->moduleLanguage['configs_lang_action']?></th>
    </tr>
  </thead>
  <tbody>
  <?if($this->languages):?>
  <?foreach($this->languages as $val):?>
    <tr>
      <td align="center"><img width="40" src="<?=models_helpers_Url::getDomain() == '/' ? '' : models_helpers_Url::getDomain();?><?=$val['smallimg']?>"/></td>
      <td align="center" style="vertical-align: middle;"><b><?=$val['name']?></b></td>
      <td align="center"><b><?=$val['short_name']?></b></td>
      <td align="center" style="vertical-align: middle;">
      <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
      <a style="cursor: pointer;" data-pk="<?=$val['id']?>" class="langdel"><?=$this->moduleLanguage['configs_lang_delete']?></a>
      <?endif;?>
      </td>
    </tr>
    <?endforeach?>
    <?endif;?>
  </tbody>
</table>
<div class="loading"></div>
<script type="text/javascript">
$(document).ready(function()
{
    $('a.langdel').click(function()
    {
        imgid = $(this).data('pk');
        $('div.loading').css('display', 'block');
        $.ajax({
            url: BASE_URL + '/configs/deleteLanguage/' + imgid,
            type: "POST",
            complete: function(data)
            {
                getLanguages();
            },
            dataType: 'html'
        });
    });
});
</script>