<table class="table table-striped small">
  <thead>
    <tr>
      <th style="text-align:center;"><?=$this->moduleLanguage['configs_params_name']?></th>
      <th style="text-align:center;"><?=$this->moduleLanguage['configs_lang_action']?></th>
    </tr>
  </thead>
  <tbody>
  <?if(!empty($this->params)):?>
  <?foreach($this->params as $val):?>
    <tr>
        <td align="center"><?=$val['name']?></td>
        <td align="center" style="vertical-align: middle;">
        <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
        <a style="cursor: pointer;" data-pk="<?=$val['id']?>" class="paramdel"><?=$this->moduleLanguage['configs_lang_delete']?></a>
        <?endif;?>
        </td>
    </tr>
    <?endforeach;?>
    <?endif;?>
  </tbody>
</table>
<div class="parloading"></div>
<script type="text/javascript">
$(document).ready(function()
{
    $('a.paramdel').click(function()
    {
        var id = $(this).data('pk');

        $('div.parloading').css('display', 'block');
        $.ajax({
            url: BASE_URL + '/configs/deleteParam/' + id,
            type: "POST",
            complete: function()
            {
                getParams();
            },
            dataType: 'html'
        });
    });
});
</script>