<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title><?=$this->moduleLanguage['title']?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->user_path?>/front-end/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->user_path?>/front-end/css/style.css" />
    </head>
    <body>
        <div style="text-align: center">
            <div class="errors-block">
                <?php echo models_helpers_Notices::instance()->getErrors();?>
            </div>
            <div class="auth-block">
                <form action="<?=$this->user_path?>/authorization/login" method="POST">
                    <div class="form-group">
                        <label><?=$this->moduleLanguage['email']?></label>
                        <input type="text" class="form-control" name="login">
                    </div>
                    <br class="clear"/>
                    <div class="form-group">
                        <label><?=$this->moduleLanguage['passw']?></label>
                        <input type="password" class="form-control" name="passw">
                    </div>
                    <br class="clear"/>
                    <div style="text-align: center; width: 100%"><input type="submit" class="btn btn-primary btn-lg" value="<?=$this->moduleLanguage['submit']?>"></div>
                    <br class="clear"/>
                </form>
            </div>
        </div>
    </body>
</html>