<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title>Admin panel</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        
        <link rel="stylesheet" type="text/css" media="all" href="<?=CSS?>/bootstrap.css" />
        <link rel="stylesheet" type="text/css" media="all" href="<?=CSS?>/style.css" />
        
        <script type="text/javascript">
        var AUTH_USER_NAME = "<?=$this->userInfo['name']?>";
        var AUTH_USER_ID = <?=$this->userInfo['id']?>;
        var BASE_URL = '<?=$this->user_path?>';
        var BASE_DOMAIN = '<?=$_SERVER['HTTP_HOST']?>';
        var EXIT_MESSAGE = '<?=$this->layoutLanguage['exit_message']?>';
        var DELETE_MESSAGE = '<?=$this->layoutLanguage['delete_message']?>';
        var YES_BUTTON = '<?=$this->layoutLanguage['yes_button']?>';
        var NO_BUTTON = '<?=$this->layoutLanguage['no_button']?>';
        <?if($this->data->_id):?>
        var EDIT_ID = <?=@$this->data->_id?>;
        <?endif?>
        </script>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="<?=JS?>/basic.js"></script>
        <script type="text/javascript" src="<?=JS?>/bootstrap.min.js"></script>
    </head> 
    <body>
        <div class="main-block">
            <?php echo models_helpers_Menu::instance()->printMenu(); ?>
            <div class="sitelink">
                <a target="_blank" href="<?=models_helpers_Url::getDomain();?>"><?=$this->layoutLanguage['gotosite']?></a>
            </div>
            <?php echo models_helpers_NavBar::instance()->getNavBar(); ?>
            <div class="userinfo-block">
                <?=$this->layoutLanguage['login_as']?> <?php echo $this->userInfo['name'];?></>
                <div class="logout"><a href="<?=$this->user_path?>/authorization/logout"> <?=$this->layoutLanguage['exit']?> <img src="<?=IMG?>/logout.png" title="<?=$this->layoutLanguage['exit']?>"/></a></div>
            </div>
            <noscript>
              <div class="messages-warnings">
                  <h1><img src="/frontend/img/admin/warning.png"/></h1>
                  <div><?=$this->layoutLanguage['js_error']?> <strong>JavaScript</strong></div>
              </div>
            </noscript>
            <div class="content-block">
                <?php echo models_helpers_Notices::instance()->getErrors()?>
                <?php echo models_helpers_Notices::instance()->getMessages()?>
                <?php echo models_helpers_Notices::instance()->getWarnings()?>
                <?php include $this->_template; ?>
            </div>
        </div>
        <nav class="navbar navbar-inverse navbar-fixed-bottom">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"><?=models_helpers_Url::getSiteName();?></a>
                </div>
                <div class="logout-bottom"><a href="<?=$this->user_path?>/authorization/logout"> <?=$this->layoutLanguage['exit']?> <img src="<?=IMG?>/logout-bot.png" title="<?=$this->layoutLanguage['exit']?>"/></a></div>
                <div class="sitelink-bottom">
                    <a target="_blank" href="<?=models_helpers_Url::getDomain();?>"><?=$this->layoutLanguage['gotosite']?></a>
                </div>
            </div>
        </nav>
    </body>
</html>