<link href="<?=CSS?>/chosen.css" rel="stylesheet">
<link href="<?=CSS?>/bootstrap-switch.css" rel="stylesheet">

<script src="<?=JS?>/highlight.js"></script>
<script src="<?=JS?>/bootstrap-switch.js"></script>
<script src="<?=JS?>/main.js"></script>
<script src="<?=JS?>/chosen.jquery.js"></script>
<script>
    $(function(){
        $(".chosen-select").chosen();
    });
</script>
<div class="col-md-12 buttons">
    <a class="btn btn-primary save" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['sizes_save']?></a>
    <a class="btn btn-success save-exit" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['sizes_save_and_exit']?></a>
    <a class="btn btn-success save-add" data-pk="<?=Request::getCurrentUrl();?>"><?=$this->moduleLanguage['sizes_save_and_create']?></a>
    <a class="btn btn-danger  exit" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'fuel/';?>"><?=$this->moduleLanguage['sizes_exit']?></a>
</div>
<form name="editForm" method="POST">
    <input type="hidden" name="author" value="<?=$this->data->_author ? $this->data->_author : $this->userInfo['id'];?>">
    <input type="hidden" name="action" value="<?=Request::instance()->getAction();?>">
    <div class="content-block col-md-12">
        <div class="col-md-3">
            <div class="form-group col-md-12">
                <label><?=$this->moduleLanguage['sizes_form_name']?></label>
                <input type="text" name="name" class="form-control" value="<?=$this->data->_name?>" placeholder="<?=$this->moduleLanguage['sizes_form_name_placeholder']?>">
            </div>
            <div class="form-group col-md-12">
                <label><?=$this->moduleLanguage['sizes_form_image']?></label>
                <input type="text" name="image" class="form-control" onclick="openKCFinder(this)" value="<?=$this->data->_image?>" placeholder="<?=$this->moduleLanguage['sizes_form_image_placeholder']?>">
            </div>
            <div class="form-group col-md-12">
                <label class="center-block" style="text-align: center;"><?=$this->moduleLanguage['sizes_form_image_preview']?></label>
                <img width="128" class="img-thumbnail center-block" src="<?=$this->data->_image?>" />
            </div>
        </div>
        <div class="col-md-9">
            <?if(Request::instance()->getAction() == 'add'):?>
                <div class="form-group col-md-12">
                    <label><?=$this->moduleLanguage['sizes_form_warning']?></label>
                </div>
            <?else:?>
                <div class="form-group col-md-3">
                    <label><?=$this->moduleLanguage['sizes_form_size']?></label>
                     <input name="size" class="form-control" placeholder="<?=$this->moduleLanguage['sizes_form_size_placeholder']?>">
                </div>
                <div class="form-group col-md-1">
                    <label><?=$this->moduleLanguage['sizes_form_size_order']?></label>
                    <input type="number" name="size_order" class="form-control" placeholder="<?=$this->moduleLanguage['sizes_form_size_order_placeholder']?>">
                </div>
                <a type="submit" class="btn btn-primary upload-size col-md-2"><?=$this->moduleLanguage['sizes_form_add']?></a>
                <div class="form-group col-md-3">
                    <label><?=$this->moduleLanguage['sizes_form_size_option']?></label>
                    <input name="size_option" class="form-control" placeholder="<?=$this->moduleLanguage['sizes_form_size_option_placeholder']?>">
                </div>
                <div class="form-group col-md-1">
                    <label><?=$this->moduleLanguage['sizes_form_size_order']?></label>
                    <input type="number" name="option_order" class="form-control" placeholder="<?=$this->moduleLanguage['sizes_form_size_order_placeholder']?>">
                </div>
                <a type="submit" class="btn btn-primary upload-opt col-md-2"><?=$this->moduleLanguage['sizes_form_add']?></a>
                <div id="options" class="ajax-bottom"></div>
            <?endif;?>
        </div>
    </div>
</form>
<script type="text/javascript">
    function openKCFinder(field)
    {
        window.KCFinder = {
            callBack: function(url)
            {
                field.value = url;
                window.KCFinder = null;
            }
        };
        window.open('<?=JS?>/kcfinder/browse.php?type=images&language=<?=strtolower(models_helpers_Url::getConfigLanguage())?>',
            'kcfinder_image', 'status=0, toolbar=0, location=0, menubar=0, ' +
            'directories=0, resizable=1, scrollbars=0, width=800, height=600'
        );
    }
    <?if(Request::instance()->getAction() == 'edit'):?>
    var id = <?=$this->data->_id?>;

    $(document).ready(function()
    {
        $('a.upload-size').on('click', function(e)
        {
            e.preventDefault();
            $('div.loading').css('display', 'block');
            var data = new FormData();

            // allow form data
            data.append('size', $('input[name="size"]').val());
            data.append('ordr', $('input[name="size_order"]').val());

            $.ajax({
                type: 'POST',
                processData: false,
                contentType: false,
                data: data,
                url: BASE_URL + '/sizes/addSize/' + id,
                success: function(jsonData)
                {
                    if(jsonData)
                        alert(jsonData);
                    getOptions();
                }
            });
        });

        $('a.upload-opt').on('click', function(e)
        {
            e.preventDefault();
            $('div.loading').css('display', 'block');
            var data = new FormData();

            // allow form data
            data.append('size_option', $('input[name="size_option"]').val());
            data.append('ordr', $('input[name="option_order"]').val());

            $.ajax({
                type: 'POST',
                processData: false,
                contentType: false,
                data: data,
                url: BASE_URL + '/sizes/addOption/' + id,
                success: function(jsonData)
                {
                    if(jsonData)
                        alert(jsonData);
                    getOptions();
                }
            });
        });
    });

    getOptions();
    // getting images
    function getOptions()
    {
        $.get(BASE_URL + '/sizes/getlist/' + id, null, function(data)
        {
            $('.col-md-12 #options').html(data);
        });
    }
    <?endif;?>
</script>