<?php $filters = $this->filter->getData(); ?>
<form class="col-md-7 search-block" id="filter" action="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkForm()?>" method="post" onsubmit="return PathGenerator(this);">
    <div class="col-md-3">
        <select class="form-control" name="status"><?=models_helpers_Options::basicOptions(models_helpers_Options::statuses(), @$filters['status'], 0, $this->moduleLanguage['sizes_search_status'])?></select>
    </div>
    <div class="col-md-4">
        <div class="input-group">
            <input type="text" name="fulltext" value="<?=@$filters['fulltext']?>" class="form-control" placeholder="<?=$this->moduleLanguage['sizes_search_text']?>"/>
            <span class="input-group-btn">
            <input type="submit" class="btn btn-default" value="<?=$this->moduleLanguage['sizes_search_button']?>"/>
            </span>
        </div>
    </div>
    <div class="col-md-1">
        <a href="#" class="clearSrch"><img src="<?=IMG?>/form/reset.png" title="<?=$this->moduleLanguage['sizes_search_reset']?>"/></a>
    </div>
</form>
<div class="col-md-5 buttons">
    <?if(models_helpers_Access::checkAccess('add')):?>
        <a class="btn btn-primary add" href="<?php echo models_helpers_Url::getValidBaseUrl().'sizes/add';?>"><?=$this->moduleLanguage['sizes_create']?></a>
    <?endif;?>
    <?if(models_helpers_Access::checkAccess('change_status')):?>
        <a class="btn btn-success activate" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'sizes/';?>"><?=$this->moduleLanguage['sizes_activation']?></a>
        <a class="btn btn-warning deactivate" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'sizes/';?>"><?=$this->moduleLanguage['sizes_deactivation']?></a>
        <a class="btn btn-danger  delete" data-pk="<?php echo models_helpers_Url::getValidBaseUrl().'sizes/';?>"><?=$this->moduleLanguage['sizes_delete']?></a>
    <?endif;?>
</div>
<div class="maincontent center-block">
    <form method="post" name="baseform">
        <table class="table table-striped table-hover small">
            <thead>
            <tr>
                <th><input type="checkbox" class="dl" name="select_all" title="<?=$this->moduleLanguage['sizes_table_check_all']?>"></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('id') ?>" class="<?php echo $this->filter->checkSortOrder('id') ?>"><?=$this->moduleLanguage['sizes_table_id']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('name') ?>" class="<?php echo $this->filter->checkSortOrder('name') ?>"><?=$this->moduleLanguage['sizes_table_name']?></a></th>
                <th><?=$this->moduleLanguage['sizes_table_logo']?></th>
                <th><?=$this->moduleLanguage['sizes_search_status']?></th>
                <th><?=$this->moduleLanguage['sizes_table_stypes']?></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('t1.date_add') ?>" class="<?php echo $this->filter->checkSortOrder('t1.date_add') ?>"><?=$this->moduleLanguage['sizes_table_date']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('t1.date_upd') ?>" class="<?php echo $this->filter->checkSortOrder('t1.date_upd') ?>"><?=$this->moduleLanguage['sizes_table_date_upd']?></a></th>
                <th><a href="<?=models_helpers_Url::getValidBaseUrl()?><?php echo $this->filter->getLinkSort('author') ?>" class="<?php echo $this->filter->checkSortOrder('author')?>"><?=$this->moduleLanguage['sizes_table_author']?></a></th>
            </tr>
            </thead>
            <tbody>
            <?if($this->datalist):?>
                <?foreach($this->datalist as $key => $val):?>
                    <tr>
                        <td><input class="il" type="checkbox" name="dellist[]" value="<?=$val['id']?>"/></td>
                        <th><?=$val['id']?></th>
                        <td>
                            <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
                            <a href="<?=models_helpers_Url::getValidBaseUrl().'sizes/edit/'.$val['id']?>">
                                <?endif;?>
                                <?=$val['name']?>
                                <?if(models_helpers_Access::checkAccess('edit') || models_helpers_Access::checkAccess('edit_your')):?>
                            </a>
                        <?endif;?>
                        </td>
                        <td><img src="<?=$val['image']?>" width="40"/></td>
                        <td>
                            <?if(models_helpers_Access::checkAccess('change_status')):?>
                            <a href="<?=models_helpers_Url::getValidBaseUrl().'fuel/changeStatus/'.$val['id']?>">
                                <?endif;?>
                                <img src="<?=IMG . '/form/'?><?=$val['status'] == 1 ? 'active' : 'deact'?>.png" />
                                <?if(models_helpers_Access::checkAccess('change_status')):?>
                            </a>
                        <?endif;?>
                        </td>
                        <td><?if (!$val['s_types']):?>
                                <?=$this->moduleLanguage['sizes_table_no_stypes']?>
                            <?else:?>
                                <?foreach ($val['s_types'] as $k=>$v):?>
                                   <?$str .= $v['size'].', '?>
                                <?endforeach;?>
                                <?echo substr($str, 0, -2)?>
                        <?endif;?>
                        </td>
                        <td><?=$val['date']?></td>
                        <td><?=$val['date_upd']?></td>
                        <td><?=$val['author']?></td>
                    </tr>
                <?endforeach;?>
            <?endif;?>
            </tbody>
        </table>
    </form>
    <?php echo $this->pagesTotal['cnt'] > 1 ? models_helpers_Paging::instance()->getPaging( $this->filter->getLinkListing(), $this->pagesTotal['cnt'], $this->filter->getPageCurrent() ): '';?>
</div>