<?if(!empty($this->sizes)):?>
<div class="col-md-6">
    <table class="table table-striped small">
        <thead>
        <tr>
            <th><?=$this->moduleLanguage['sizes_form_sizes_table_types']?></th>
            <?foreach ($this->sizes as $head):?>
            <th style="text-align:center;"><?=$head['size']?></th>
            <?endforeach;?>
        </tr>
        </thead>
        <tbody>
        <?if(!empty($this->options)):?>
        <?foreach ($this->options as $val):?>
            <tr class="success">
                <td><?=$val['size_option']?></td>
                <?foreach ($this->sizes as $head):?>
                    <td></td>
                <?endforeach;?>
            </tr>
        <?endforeach;?>
        <?endif;?>
        </tbody>
    </table>
</div>
<?if(!empty($this->sizes)):?>
<div class="col-md-2">
    <table class="table table-striped small">
        <thead>
        <tr>
            <th><?=$this->moduleLanguage['sizes_form_sizes_table']?></th>
            <th>#</th>
            <th style="text-align:center;"><?=$this->moduleLanguage['sizes_form_sizes_table_action']?></th>
        </tr>
        </thead>
        <tbody>
        <?foreach ($this->sizes as $val):?>
            <tr class="success">
                <td><?=$val['size']?></td>
                <td><?=$val['ordr']?></td>
                <td align="center" style="vertical-align: middle;"><a style="cursor: pointer;" data-id="<?=$val['id']?>" class="sizedel"><?=$this->moduleLanguage['sizes_form_delete']?></a></td>
            </tr>
        <?endforeach;?>
        </tbody>
    </table>
</div>
<?endif;?>
<?if(!empty($this->options)):?>
    <div class="col-md-4">
        <table class="table table-striped small">
            <thead>
            <tr>
                <th><?=$this->moduleLanguage['sizes_form_sizes_table_types']?></th>
                <th>#</th>
                <th style="text-align:center;"><?=$this->moduleLanguage['sizes_form_sizes_table_action']?></th>
            </tr>
            </thead>
            <tbody>
            <?foreach ($this->options as $val):?>
                <tr class="success">
                    <td><?=$val['size_option']?></td>
                    <td><?=$val['ordr']?></td>
                    <td align="center" style="vertical-align: middle;"><a style="cursor: pointer;" data-id="<?=$val['id']?>" class="optdel"><?=$this->moduleLanguage['sizes_form_delete']?></a></td>
                </tr>
            <?endforeach;?>
            </tbody>
        </table>
    </div>
<?endif;?>
<div class="loading"></div>
<script type="text/javascript">
    $(document).ready(function()
    {
        $('a.sizedel').click(function()
        {
            var id = $(this).data('id');
            if (window.confirm("<?=$this->moduleLanguage['sizes_form_delete_size']?>"))
            {
                $('div.loading').css('display', 'block');
                $.ajax({
                    url: BASE_URL + '/sizes/deleteSize/' + id,
                    type: "POST",

                    complete: function()
                    {
                        getOptions();
                    },
                    dataType: 'html'

                });
            }
        });

        $('a.optdel').click(function()
        {
            var id = $(this).data('id');
            if (window.confirm("<?=$this->moduleLanguage['sizes_form_delete_size']?>"))
            {
                $('div.loading').css('display', 'block');
                $.ajax({
                    url: BASE_URL + '/sizes/deleteOption/' + id,
                    type: "POST",

                    complete: function () {
                        getOptions();
                    },
                    dataType: 'html'

                });
            }
        });
    });
</script>
<?endif;?>